name: build whl and uploads

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-cpu:
    runs-on: windows-2019
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      BAZEL_PATH: "D:\\bazel.exe"
      TEMP: 'D:\\Temp'
      TMP: 'D:\\Temp'
      PYTHONUNBUFFERED: '1'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download Bazelisk
      run: curl -k -L https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-windows-amd64.exe -o $env:BAZEL_PATH

    - uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('build-requirements-*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    #============#
    # Python 3.9 #
    #============#
    - name: py39
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: py39 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py39.txt"
    - name: py39 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cpu.ps1 -bazel_path $env:BAZEL_PATH
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.8 #
    #============#
    - name: py38
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: py38 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py38.txt"
    - name: py38 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cpu.ps1 -bazel_path $env:BAZEL_PATH
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.7 #
    #============#
    - name: py37
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: py37 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py37.txt"
    - name: py37 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cpu.ps1 -bazel_path $env:BAZEL_PATH
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

  build-cuda101:
    runs-on: windows-2019
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      BAZEL_PATH: "D:\\bazel.exe"
      TEMP: 'D:\\Temp'
      TMP: 'D:\\Temp'
      PYTHONUNBUFFERED: '1'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download Bazelisk
      run: curl -k -L https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-windows-amd64.exe -o $env:BAZEL_PATH

    - name: Install CUDA 10.1
      run: |
        curl -k -L https://whls.blob.core.windows.net/ci-files/v10.1.7z -o cuda.7z
        7z x cuda.7z -o'D:/CUDA'
        rm cuda.7z
        ls D:/CUDA/v10.1

    - uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('build-requirements-*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    #============#
    # Python 3.9 #
    #============#
    - name: py39
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: py39 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py39.txt"
    - name: py39 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '10.1' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.8 #
    #============#
    - name: py38
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: py38 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py38.txt"
    - name: py38 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '10.1' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.7 #
    #============#
    - name: py37
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: py37 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py37.txt"
    - name: py37 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '10.1' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

  build-cuda112:
    runs-on: windows-2019
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      BAZEL_PATH: "D:\\bazel.exe"
      TEMP: 'D:\\Temp'
      TMP: 'D:\\Temp'
      PYTHONUNBUFFERED: '1'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download Bazelisk
      run: curl -k -L https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-windows-amd64.exe -o $env:BAZEL_PATH

    - name: Install CUDA 11.2
      run: |
        curl -k -L https://whls.blob.core.windows.net/ci-files/v11.2.7z -o cuda.7z
        7z x cuda.7z -o'D:/CUDA'
        rm cuda.7z
        ls D:/CUDA/v11.2

    - uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('build-requirements-*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    #============#
    # Python 3.9 #
    #============#
    - name: py39
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: py39 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py39.txt"
    - name: py39 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '11.2' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.8 #
    #============#
    - name: py38
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: py38 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py38.txt"
    - name: py38 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '11.2' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"

    #============#
    # Python 3.7 #
    #============#
    - name: py37
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: py37 pip install
      run: pip install -r "$env:GITHUB_WORKSPACE/build-requirements-py37.txt"
    - name: py37 build whl and upload
      run: |
        cd "$env:GITHUB_WORKSPACE/jax"
        ../bazel-build-cuda.ps1 -bazel_path $env:BAZEL_PATH -cuda_version '11.2' -cuda_prefix 'D:/CUDA'
        az storage blob upload-batch -d unstable -s "$env:GITHUB_WORKSPACE/jax/bazel-dist" --pattern '*.whl'
        rm -Recurse -Force "$env:GITHUB_WORKSPACE/jax/bazel-dist"
